
import { ServiceDetail } from './types';

export const COLORS = {
  CREAM: '#FFF2EC',
  INK: '#1a1a1a',
  GOLD: '#C5A059',
  SIGNAL_RED: '#E21E3F',
};

export const SERVICES: ServiceDetail[] = [
  {
    id: 'pillar1',
    title: 'WEBSITES & E-COMMERCE',
    subtitle: 'The Face',
    technicalLabel: '[ YOUR ONLINE STOREFRONT ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you losing leads in spreadsheets?',
    description: 'Your website is the front door to your business. I build sites that don\'t just look good — they capture leads, sell products, and feed your CRM automatically.',
    features: ['Smart Lead Forms', 'Inventory Connected to Sales', 'Fast, Mobile-First Design'],
    visualPrompt: 'geometric',
    bgImage: '',
    icon: 'Target',
  },
  {
    id: 'pillar2',
    title: 'CRM & LEAD TRACKING',
    subtitle: 'The Brain',
    technicalLabel: '[ NEVER LOSE A LEAD ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Do you know exactly where every deal is stuck?',
    description: 'If it\'s not in the CRM, it didn\'t happen. I set up tracking systems so every lead, every call, and every deal is logged — automatically.',
    features: ['Visual Deal Pipeline', 'Clean, Accurate Data', 'Auto Follow-Up Reminders'],
    visualPrompt: 'network',
    bgImage: '',
    icon: 'Database',
  },
  {
    id: 'pillar3',
    title: 'AUTOMATION',
    subtitle: 'The Muscle',
    technicalLabel: '[ INVOICES & ADMIN ON AUTOPILOT ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you manually typing invoices and contracts?',
    description: 'Stop re-typing the same data into three different apps. I connect your systems so information flows automatically — quotes to invoices, leads to CRM, orders to fulfilment.',
    features: ['Instant Data Sync', 'Smart Email Sequences', 'Auto-Generated Invoices & Contracts'],
    visualPrompt: 'flow',
    bgImage: '',
    icon: 'Zap',
  },
  {
    id: 'pillar4',
    title: 'AI ASSISTANTS',
    subtitle: 'The Voice',
    technicalLabel: '[ BOTS THAT TALK & THINK ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is your team answering the same 5 questions all day?',
    description: 'I build AI bots that answer your phone, reply to enquiries, and qualify leads — 24/7, even while you sleep. They sound human, and they never take a sick day.',
    features: ['AI Phone Answering', 'Internal Knowledge Bots', 'Built-In Safety Rules'],
    visualPrompt: 'neural',
    bgImage: '',
    icon: 'Cpu',
  },
  {
    id: 'pillar5',
    title: 'CONTENT SYSTEMS',
    subtitle: 'The Presence',
    technicalLabel: '[ CREATE ONCE, POST EVERYWHERE ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is content creation taking hours instead of minutes?',
    description: 'You talk, I turn it into content. One voice note becomes a blog, 5 social posts, and a newsletter — all published automatically across every platform.',
    features: ['AI Voice & Video Cloning', 'Auto-Post to All Platforms', 'YouTube & Podcast Setup'],
    visualPrompt: 'sequential',
    bgImage: '',
    icon: 'Layers',
  },
  {
    id: 'pillar6',
    title: 'TEAM TRAINING',
    subtitle: 'The Soul',
    technicalLabel: '[ MAKE YOUR TEAM USE IT ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Did you buy software that nobody uses?',
    description: 'New software only works if your team actually uses it. I create short training videos and SOPs that make adoption easy — no 3-hour Zoom calls, no confusion.',
    features: ['Bite-Sized Training Videos', 'Step-by-Step Guides', 'Team Q&A Library'],
    visualPrompt: 'waves',
    bgImage: '',
    icon: 'Users',
  },
  {
    id: 'pillar7',
    title: 'DASHBOARDS & REPORTING',
    subtitle: 'The Eyes',
    technicalLabel: '[ SEE YOUR NUMBERS IN REAL-TIME ]',
    systemGroup: 'SEE CLEARLY',
    symptom: 'Are you steering the business by gut feeling?',
    description: 'Stop guessing. I build dashboards that show your revenue, margins, and pipeline in real-time — so you make decisions based on data, not gut feeling.',
    features: ['Live Revenue Tracking', 'Forecasting & Projections', 'One-Screen Business Health'],
    visualPrompt: 'dashboard',
    bgImage: '',
    icon: 'BarChart3',
  }
];
