
import { ServiceDetail } from './types';

export const COLORS = {
  CREAM: '#FFF2EC',
  INK: '#1a1a1a',
  GOLD: '#C5A059',
  SIGNAL_RED: '#E21E3F',
};

export const SERVICES: ServiceDetail[] = [
  {
    id: 'pillar-1',
    title: 'DIGITAL REVENUE',
    subtitle: 'The Face',
    technicalLabel: '[ WORDPRESS_&_SHOPIFY_DEV ]',
    systemGroup: 'ACQUISITION_SYS',
    symptom: 'Are you losing leads in spreadsheets?',
    description: 'The entry point. I engineer a high-performance digital catchment that feeds the rest of the ecosystem. It is not just a website; it is a conversion engine.',
    features: ['Lead Capture Architecture', 'Retail Inventory Sync', 'Digital Theatre & UX'],
    visualPrompt: 'geometric',
    bgImage: '',
    icon: 'Target',
  },
  {
    id: 'pillar-2',
    title: 'CRM INTELLIGENCE',
    subtitle: 'The Brain',
    technicalLabel: '[ DATA_PIPELINE_ARCHITECTURE ]',
    systemGroup: 'ACQUISITION_SYS',
    symptom: 'Do you know exactly where every deal is stuck?',
    description: 'The single source of truth. A nervous system that tracks every lead and ensures no revenue is lost to human error or memory lapses.',
    features: ['Pipeline Velocity', 'Data Hygiene Protocols', 'Automated Follow-up'],
    visualPrompt: 'network',
    bgImage: '',
    icon: 'Database',
  },
  {
    id: 'pillar-3',
    title: 'AUTOMATION ARCHITECTURE',
    subtitle: 'The Muscle',
    technicalLabel: '[ FINANCE_&_ADMIN_AUTOPILOT ]',
    systemGroup: 'ACQUISITION_SYS',
    symptom: 'Are you manually typing invoices and contracts?',
    description: 'Code leverage. I decouple revenue from hours worked by moving data between systems without human intervention, removing the "Administrative Drag."',
    features: ['Zero-Lag Operations', 'Behavioral Email Engines', 'Fulfillment Autopilot'],
    visualPrompt: 'flow',
    bgImage: '',
    icon: 'Zap',
  },
  {
    id: 'pillar-4',
    title: 'COGNITIVE INFRASTRUCTURE',
    subtitle: 'The Voice',
    technicalLabel: '[ LLM_AGENTIC_WORKFORCE ]',
    systemGroup: 'VELOCITY_SYS',
    symptom: 'Is your team answering the same 5 questions all day?',
    description: 'Agentic AI. I build digital employees that can reason, speak, and qualify leads 24/7 on your behalf, scaling your human bandwidth.',
    features: ['Voice Agents', 'Internal Analyst Bots', 'Compliance Guardrails'],
    visualPrompt: 'neural',
    bgImage: '',
    icon: 'Cpu',
  },
  {
    id: 'pillar-5',
    title: 'MEDIA LOGISTICS',
    subtitle: 'The Presence',
    technicalLabel: '[ SYNTHETIC_CONTENT_GRID ]',
    systemGroup: 'VELOCITY_SYS',
    symptom: 'Is content creation taking hours instead of minutes?',
    description: 'A content supply chain. I turn raw expertise into omni-channel authority assets without you needing a camera crew or a marketing team.',
    features: ['Synthetic Studio', 'Distribution Grid', 'Video SEO Matrix'],
    visualPrompt: 'sequential',
    bgImage: '',
    icon: 'Layers',
  },
  {
    id: 'pillar-6',
    title: 'ADOPTION ARCHITECTURE',
    subtitle: 'The Soul',
    technicalLabel: '[ INTERNAL_PROTOCOL_SYNC ]',
    systemGroup: 'VELOCITY_SYS',
    symptom: 'Did you buy software that nobody uses?',
    description: 'Change management. I engineer the behavioral shift so your staff actually use the tools we build, preventing "Digital Rejection."',
    features: ['Micro-Learning Matrix', 'Visual SOPs', 'Internal Pods'],
    visualPrompt: 'waves',
    bgImage: '',
    icon: 'Users',
  },
  {
    id: 'pillar-7',
    title: 'INTELLIGENCE ARCHITECTURE',
    subtitle: 'The Eyes',
    technicalLabel: '[ PREDICTIVE_REVENUE_MODELING ]',
    systemGroup: 'INTELLIGENCE_SYS',
    symptom: 'Are you steering the business by gut feeling?',
    description: 'Clarity of vision. A control tower that moves you from "gut feeling" to evidence-based growth, giving you the confidence to scale.',
    features: ['Revenue Pulse', 'Predictive Models', 'Executive Dashboards'],
    visualPrompt: 'dashboard',
    bgImage: '',
    icon: 'BarChart3',
  }
];
