
import { ServiceDetail } from './types';

export const COLORS = {
  CREAM: '#FFF2EC',
  INK: '#1a1a1a',
  GOLD: '#C5A059',
  SIGNAL_RED: '#E21E3F',
};

export const SERVICES: ServiceDetail[] = [
  {
    id: 'pillar1',
    title: 'Websites',
    subtitle: 'The Face',
    technicalLabel: '[ YOUR ONLINE STOREFRONT ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you losing leads in spreadsheets?',
    description: 'Your website should capture leads and sell products, not just sit there looking pretty. I build sites that work while you sleep.',
    features: ['Smart Lead Forms', 'Inventory Connected to Sales', 'Fast, Mobile-First Design'],
    visualPrompt: 'geometric',
    bgImage: '',
    icon: 'Target',
  },
  {
    id: 'pillar2',
    title: 'CRM',
    subtitle: 'The Brain',
    technicalLabel: '[ NEVER LOSE A LEAD ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Do you know exactly where every deal is stuck?',
    description: 'If it\'s not in the CRM, it didn\'t happen. I set up tracking so every lead, call, and deal is logged automatically.',
    features: ['Visual Deal Pipeline', 'Clean, Accurate Data', 'Auto Follow-Up Reminders'],
    visualPrompt: 'network',
    bgImage: '',
    icon: 'Database',
  },
  {
    id: 'pillar3',
    title: 'Automation',
    subtitle: 'The Muscle',
    technicalLabel: '[ ADMIN ON AUTOPILOT ]',
    systemGroup: 'GET CLIENTS',
    symptom: 'Are you manually typing invoices and contracts?',
    description: 'Stop re-typing the same data into three different apps. I connect your systems so invoices, follow-ups, and admin run on autopilot.',
    features: ['Instant Data Sync', 'Smart Email Sequences', 'Auto-Generated Invoices'],
    visualPrompt: 'flow',
    bgImage: '',
    icon: 'Zap',
  },
  {
    id: 'pillar4',
    title: 'AI Assistants',
    subtitle: 'The Voice',
    technicalLabel: '[ BOTS THAT TALK AND THINK ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is your team answering the same 5 questions all day?',
    description: 'I build AI bots that answer your phone, reply to enquiries, and qualify leads 24/7. They sound human and never take a sick day.',
    features: ['AI Phone Answering', 'Internal Knowledge Bots', 'Built-In Safety Rules'],
    visualPrompt: 'neural',
    bgImage: '',
    icon: 'Cpu',
  },
  {
    id: 'pillar5',
    title: 'Content Systems',
    subtitle: 'The Presence',
    technicalLabel: '[ CREATE ONCE, POST EVERYWHERE ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Is content creation taking hours instead of minutes?',
    description: 'You talk, I turn it into content. One voice note becomes a blog, social posts, and a newsletter, all published automatically.',
    features: ['AI Voice & Video Cloning', 'Auto-Post to All Platforms', 'YouTube & Podcast Setup'],
    visualPrompt: 'sequential',
    bgImage: '',
    icon: 'Layers',
  },
  {
    id: 'pillar6',
    title: 'Team Training',
    subtitle: 'The Soul',
    technicalLabel: '[ MAKE YOUR TEAM USE IT ]',
    systemGroup: 'SCALE FASTER',
    symptom: 'Did you buy software that nobody uses?',
    description: 'New software only works if your team actually uses it. I create short training videos and guides that make adoption easy.',
    features: ['Bite-Sized Training Videos', 'Step-by-Step Guides', 'Team Q&A Library'],
    visualPrompt: 'waves',
    bgImage: '',
    icon: 'Users',
  },
  {
    id: 'pillar7',
    title: 'Dashboards',
    subtitle: 'The Eyes',
    technicalLabel: '[ YOUR NUMBERS IN REAL TIME ]',
    systemGroup: 'SEE CLEARLY',
    symptom: 'Are you steering the business by gut feeling?',
    description: 'Stop guessing. I build dashboards that show your revenue, margins, and pipeline in real time so you make decisions based on data.',
    features: ['Live Revenue Tracking', 'Forecasting & Projections', 'One-Screen Business Health'],
    visualPrompt: 'dashboard',
    bgImage: '',
    icon: 'BarChart3',
  }
];
